In [1]:
import os
import point_cloud_utils as pcu
import numpy as np
from tqdm import tqdm
import torch
import argparse
import objaverse
import trimesh
from scipy.interpolate import interpn
import random
import multiprocessing
import point_cloud_utils as pcu


# Download objaverse objects

In [2]:
random.seed(42)

uids = objaverse.load_uids()
random_object_uids = random.sample(uids, 100)

random_object_uids

['f82039689f504922995936c68484aa61',
 'fb42332b3f5e491cb0c4b5ba7ed6f374',
 'd633b522306b4499a8e6f1ac5f517864',
 '89da97b84f4d4fbc825bf3e914d45e92',
 '32aaba5aa1954cb898111bf884404039',
 'f84c8cbd56d94be18a727c66de2c2d51',
 '6afcf8814d494372a4f3f7e3b99219ba',
 '38cb6584bb734d729baf712da41b141f',
 'f9b8b1cea04243a7bf706c4565027187',
 '306aa51bb3c24464886dce788547e6cb',
 'df4d2da4e9934b82b30f9bcab685a0fd',
 '45509feed4534fa1a34567ae82c457cf',
 'b86569c202fa455b8d221e90c5588cc7',
 '00ae6eda19634ee6b0a4a52789c9ff90',
 'bfd6abe69bde4ee7806ef3fa483b0655',
 '1b1c987aa5914a4f85eecca0a6ba9b4e',
 '7842c2ad6fe74224974d64958baea75d',
 'a018d452856f4452958e081f77cdc253',
 '9e6bd36b7b94412a9c71fdc34561a934',
 '6845849028774ca782f0e2e221c69944',
 '60a206c7952c420e844640de850f4fcf',
 'd0ca35386b0b48418f8669da1bea0923',
 '61955029fd2c48d9a6eb6c6097f93b6c',
 '329684e1e63d4d16bcf519cc9571c1fb',
 '06d70683684b4b4cbc3da27c5507ee6a',
 '71aad2b07e5a4d4bb75f4acbdb6a1aa2',
 '4954590a8ea7404f9c4a83a446313f07',
 

In [3]:
processes = multiprocessing.cpu_count()

objects = objaverse.load_objects(
    uids=random_object_uids,
    download_processes=processes
)
objects

{'f82039689f504922995936c68484aa61': 'C:\\Users\\Thomas Benzshawel\\.objaverse\\hf-objaverse-v1\\glbs/000-120/f82039689f504922995936c68484aa61.glb',
 'fb42332b3f5e491cb0c4b5ba7ed6f374': 'C:\\Users\\Thomas Benzshawel\\.objaverse\\hf-objaverse-v1\\glbs/000-003/fb42332b3f5e491cb0c4b5ba7ed6f374.glb',
 'd633b522306b4499a8e6f1ac5f517864': 'C:\\Users\\Thomas Benzshawel\\.objaverse\\hf-objaverse-v1\\glbs/000-011/d633b522306b4499a8e6f1ac5f517864.glb',
 '89da97b84f4d4fbc825bf3e914d45e92': 'C:\\Users\\Thomas Benzshawel\\.objaverse\\hf-objaverse-v1\\glbs/000-143/89da97b84f4d4fbc825bf3e914d45e92.glb',
 '32aaba5aa1954cb898111bf884404039': 'C:\\Users\\Thomas Benzshawel\\.objaverse\\hf-objaverse-v1\\glbs/000-136/32aaba5aa1954cb898111bf884404039.glb',
 'f84c8cbd56d94be18a727c66de2c2d51': 'C:\\Users\\Thomas Benzshawel\\.objaverse\\hf-objaverse-v1\\glbs/000-110/f84c8cbd56d94be18a727c66de2c2d51.glb',
 '6afcf8814d494372a4f3f7e3b99219ba': 'C:\\Users\\Thomas Benzshawel\\.objaverse\\hf-objaverse-v1\\glbs/000-

In [4]:
def find_glb_files(directory):
    glb_files = []
    for root, dirs, files in os.walk(directory):
        for file in files:
            if file.endswith('.glb'):
                glb_files.append(os.path.join(root, file))
    return glb_files

# Testing Voxelizing

In [5]:
# Usage
objaverse_path = "C:\\Users\\Thomas Benzshawel\\.objaverse\\hf-objaverse-v1\\glbs"
target_path = "C:\\Repos\\kedziora_research\\kedziora_research\\summer_dev\\voxelized"

In [6]:
mesh = trimesh.load(list(objects.values())[0], force='mesh')
mesh.show()

In [7]:
#turn the glb into .obj
obj_path = os.path.join(target_path, "temp.obj")
mesh.export(obj_path)

v, f = pcu.load_mesh_vf(os.path.join("C:\\Repos\\kedziora_research\\kedziora_research\\summer_dev\\voxelized\\temp.obj"))



In [8]:
#compare trimesh and pcu v and f

vertices = mesh.vertices
faces = mesh.faces

print(vertices, vertices.shape)
print(v, v.shape)

print(faces, faces.shape)
print(f, f.shape)

[[-0.00980579  0.07694813 -0.00930066]
 [-0.0074037   0.07712334 -0.00941159]
 [-0.00725379  0.07720527 -0.01011493]
 ...
 [ 0.00688698  0.07342479  0.01010424]
 [ 0.00748055  0.07342478  0.0098431 ]
 [ 0.00803768  0.07342479  0.00965734]] (16679, 3)
[[-0.00980579  0.07694813 -0.00930066]
 [-0.0074037   0.07712334 -0.00941159]
 [-0.00725379  0.07720527 -0.01011493]
 ...
 [ 0.00688698  0.07342479  0.01010424]
 [ 0.00748055  0.07342478  0.0098431 ]
 [ 0.00803768  0.07342479  0.00965734]] (16679, 3)
[[    0     1     2]
 [    0     2     3]
 [    1     4     5]
 ...
 [16678 15146 15145]
 [16451 16678 15145]
 [16451 15145 15110]] (31958, 3)
[[    0     1     2]
 [    0     2     3]
 [    1     4     5]
 ...
 [16678 15146 15145]
 [16451 16678 15145]
 [16451 15145 15110]] (31958, 3)


Pcu and trimesh seem to handle the vertices and faces the same way, this is good for us.

In [9]:
num_vox = 512
max_num_vox = 512
sample_pcs_num = 1_000_000
vox_size = 1.0 / max_num_vox

In [10]:
try:
    fid, bc = pcu.sample_mesh_random(v, f, sample_pcs_num)
    ref_xyz = pcu.interpolate_barycentric_coords(f, fid, bc, v)
except:
    fid, bc = pcu.sample_mesh_random(v, f, sample_pcs_num)
    ref_xyz = pcu.interpolate_barycentric_coords(f, fid, bc, v)
    

In [11]:
n = pcu.estimate_mesh_face_normals(v, f)
ref_normal = n[fid]
        
ijk = pcu.voxelize_triangle_mesh(v, f.astype(np.int32), vox_size, np.zeros(3))

In [ ]:
# TODO Need to create an alternative to this
# grid = fvdb.sparse_grid_from_ijk(fvdb.JaggedTensor([torch.from_numpy(ijk).cuda()]), voxel_sizes=vox_size, origins=[vox_size / 2.] * 3)

In [ ]:
# get normal ref
ref_xyz = torch.from_numpy(ref_xyz).float().cuda()
ref_normal = torch.from_numpy(ref_normal).float().cuda()

# TODO Replace this with a different method
######################################################
# input_normal = grid.splat_trilinear(fvdb.JaggedTensor(ref_xyz), fvdb.JaggedTensor(ref_normal))
# # normalize normal
# input_normal.jdata /= (input_normal.jdata.norm(dim=1, keepdim=True) + 1e-6) # avoid nan

#################################################################
        
# normalize xyz to conv-onet scale
xyz = grid.grid_to_world(grid.ijk.float()).jdata
xyz_norm = xyz * 128 / 100
ref_xyz = ref_xyz * 128 / 100

# TODO Replace this with a different method
###########################################
# convert to fvdb_grid format
# if num_vox == 512:
#     # not splatting
#     target_voxel_size = 0.0025
#     target_grid = fvdb.sparse_grid_from_points(
#             fvdb.JaggedTensor(xyz_norm), voxel_sizes=target_voxel_size, origins=[target_voxel_size / 2.] * 3)
# elif num_vox == 16:
#     # splatting
#     target_voxel_size = 0.08
#     target_grid = fvdb.sparse_grid_from_nearest_voxels_to_points(
#                 fvdb.JaggedTensor(xyz_norm), voxel_sizes=target_voxel_size, origins=[target_voxel_size / 2.] * 3)
# elif num_vox == 128:
#     # splatting
#     target_voxel_size = 0.01
#     target_grid = fvdb.sparse_grid_from_nearest_voxels_to_points(
#                 fvdb.JaggedTensor(xyz_norm), voxel_sizes=target_voxel_size, origins=[target_voxel_size / 2.] * 3)
# elif num_vox == 256:
#     target_voxel_size = 0.005
#     target_grid = fvdb.sparse_grid_from_nearest_voxels_to_points(
#                 fvdb.JaggedTensor(xyz_norm), voxel_sizes=target_voxel_size, origins=[target_voxel_size / 2.] * 3)
# elif num_vox == 1024:
#     target_voxel_size = 0.00125
#     target_grid = fvdb.sparse_grid_from_points(
#                 fvdb.JaggedTensor(xyz_norm), voxel_sizes=target_voxel_size, origins=[target_voxel_size / 2.] * 3)
# else:
#     raise NotImplementedError

# # get target normal
# target_normal = target_grid.splat_trilinear(fvdb.JaggedTensor(ref_xyz), fvdb.JaggedTensor(ref_normal))
# target_normal.jdata /= (target_normal.jdata.norm(dim=1, keepdim=True) + 1e-6)

######################

save_dict = {
    "points": target_grid.to("cpu"),
    "normals": target_normal.cpu(),
    "ref_xyz": ref_xyz.cpu(),
    "ref_normal": ref_normal.cpu(),
}

torch.save(save_dict, target_path)